CREATE TABLE MD_IDBASE(
	ID_PREFIX bigint not null 
);
GO
ALTER TABLE MD_IDBASE ADD CONSTRAINT chkMAX CHECK (ID_PREFIX <21); --max 20 domains
GO
insert into MD_IDBASE(ID_PREFIX) values(1);
GO
CREATE TABLE MD_IDGEN(
	ID bigint IDENTITY(400,1) NOT NULL,
	DUAL smallint NULL
)
GO
ALTER TABLE MD_IDGEN ADD CONSTRAINT chk_MAX CHECK (ID<1474835); --max int select (20*1000000 + 1474835)*100
GO

CREATE PROCEDURE get_id_base
AS begin
  INSERT INTO MD_IDGEN (DUAL) VALUES (1);
  SELECT MD_IDBASE.ID_PREFIX*1000000 + IDENT_CURRENT('MD_IDGEN') as NewGenID FROM MD_IDBASE;
  DELETE FROM MD_IDGEN WHERE ID=IDENT_CURRENT('MD_IDGEN');
end  
GO


create function dbo.getCurrentID ()
RETURNS bigint
as
begin
 DECLARE @ID int;
 SELECT @ID=MD_IDBASE.ID_PREFIX*1000000 + IDENT_CURRENT('MD_IDGEN') FROM MD_IDBASE;
 RETURN @ID;
end
GO 
CREATE PROCEDURE get_id_base_func
  @id bigint OUTPUT
AS begin
  INSERT INTO MD_IDGEN (DUAL) VALUES (0);
  SELECT @ID=MD_IDBASE.ID_PREFIX*1000000 + IDENT_CURRENT('MD_IDGEN') FROM MD_IDBASE;
  DELETE FROM MD_IDGEN WHERE ID=IDENT_CURRENT('MD_IDGEN');
end  
GO
