// This file is generated automatically and contain definition for code insight.
// Ignored by UnityBase server because name start from "_".
// Do not modify this file directly. Run ub cmd/createCodeInsightHelper -help for details

/**
* BLOBTest
* @mixes EventEmitter
* @mixes RequiredModule
*/
var tst_blob = {
  /**
   * Reference to entity metadata
   * @type {TubEntity}
   */
  entity: null
}

/**
* Attributes of "BLOBTest"
* @class
*/
function tst_blob_object () {
    /**
    *
    *
    * @type {Number}
    */
  this.ID = 0
    /**
    * Description
    * @type {String}
    */
  this.description = ''
    /**
    * BLOB
    * Long BLOB value
    * @type {ArrayBuffer}
    */
  this.blb = undefined
}

/**
* COD docs kind
* @mixes EventEmitter
* @mixes RequiredModule
*/
var tst_category = {
  /**
   * Reference to entity metadata
   * @type {TubEntity}
   */
  entity: null
}

/**
* Attributes of "COD docs kind"
* @class
*/
function tst_category_object () {
    /**
    *
    *
    * @type {Number}
    */
  this.ID = 0
    /**
    * Code
    * Internal code of document kind
    * @type {String}
    */
  this.code = ''
    /**
    * InstanceID
    * @type {Number}
    */
  this.instanceID = 0
    /**
    * Allow for user (ref -> uba_user)
    * @type {Number}
    */
  this.ubUser = 0
}

/**
* CLOBTest
* @mixes EventEmitter
* @mixes RequiredModule
*/
var tst_clob = {
  /**
   * Reference to entity metadata
   * @type {TubEntity}
   */
  entity: null
}

/**
* Attributes of "CLOBTest"
* @class
*/
function tst_clob_object () {
    /**
    *
    *
    * @type {Number}
    */
  this.ID = 0
    /**
    * Description
    * @type {String}
    */
  this.description = ''
    /**
    * Text100
    * Long text value truncated to 100
    * @type {String}
    */
  this.text100 = ''
    /**
    * Text2
    * Long text value truncated to 2
    * @type {String}
    */
  this.text2 = ''
    /**
    * Text2000
    * Long text value truncated to 2000
    * @type {String}
    */
  this.text2000 = ''
    /**
    *
    * Long text 1900
    * @type {String}
    */
  this.textN = ''
    /**
    * Code
    * @type {String}
    */
  this.code = ''
    /**
    * Text100(100..)
    * Mixin &quot;clobTruncate&quot; autogenerated attribute for truncate text value of &quot;text100&quot; attribute
    *
    * @type {String}
    */
  this.mi_tr_text100 = ''
    /**
    * Text2(2..)
    * Mixin &quot;clobTruncate&quot; autogenerated attribute for truncate text value of &quot;text2&quot; attribute
    *
    * @type {String}
    */
  this.mi_tr_text2 = ''
    /**
    * Text2000(2000..)
    * Mixin &quot;clobTruncate&quot; autogenerated attribute for truncate text value of &quot;text2000&quot; attribute
    *
    * @type {String}
    */
  this.mi_tr_text2000 = ''
}

/**
* Test crypto
* @mixes EventEmitter
* @mixes RequiredModule
*/
var tst_crypto = {
  /**
   * Reference to entity metadata
   * @type {TubEntity}
   */
  entity: null
}

/**
* Attributes of "Test crypto"
* @class
*/
function tst_crypto_object () {
}

/**
* tst_dictionary
* @mixes EventEmitter
* @mixes RequiredModule
*/
var tst_dictionary = {
  /**
   * Reference to entity metadata
   * @type {TubEntity}
   */
  entity: null
}

/**
* Attributes of "tst_dictionary"
* @class
*/
function tst_dictionary_object () {
    /**
    *
    *
    * @type {Number}
    */
  this.ID = 0
    /**
    * Code
    * Code
    * @type {String}
    */
  this.code = ''
    /**
    * Caption
    * Caption
    * @type {String}
    */
  this.caption = ''
    /**
    * filterValue
    * @type {Number}
    */
  this.filterValue = 0
    /**
    * Currency Data
    * @type {Number}
    */
  this.currencyValue = 0
    /**
    * Назва
    * @type {String}
    */
  this.calculated = ''
    /**
    * Test boolean column
    * @type {Boolean}
    */
  this.booleanColumn = undefined
    /**
    *  (ref -> uba_user)
    * Row owner
    *
    * @type {Number}
    */
  this.mi_owner = 0
    /**
    *
    * Creation date
    *
    * @type {Date}
    */
  this.mi_createDate = new Date()
    /**
    *  (ref -> uba_user)
    * User who create row
    *
    * @type {Number}
    */
  this.mi_createUser = 0
    /**
    *
    * Modification date
    *
    * @type {Date}
    */
  this.mi_modifyDate = new Date()
    /**
    *  (ref -> uba_user)
    * User who modify row
    *
    * @type {Number}
    */
  this.mi_modifyUser = 0
}

/**
* DocumentTest
* @mixes EventEmitter
* @mixes RequiredModule
*/
var tst_document = {
  /**
   * Reference to entity metadata
   * @type {TubEntity}
   */
  entity: null
}

/**
* Attributes of "DocumentTest"
* @class
*/
function tst_document_object () {
    /**
    *
    *
    * @type {Number}
    */
  this.ID = 0
    /**
    * Code
    * @type {String}
    */
  this.code = ''
    /**
    * Document date
    * @type {Date}
    */
  this.docDate = new Date()
    /**
    * income date
    * @type {Date}
    */
  this.incomeDate = new Date()
    /**
    * reg date
    * @type {Date}
    */
  this.regDate = new Date()
    /**
    * Category (ref -> tst_category)
    * @type {Number}
    */
  this.category = 0
    /**
    * Favorites (ref -> tst_category)
    * @type {Number}
    */
  this.favorites = 0
    /**
    * Favorites (ref -> tst_category)
    * @type {Number}
    */
  this.favorites2 = 0
    /**
    * Document full date
    * @type {Date}
    */
  this.docDateTime = new Date()
    /**
    * Description
    * @type {String}
    */
  this.description = ''
    /**
    * Simple
    * Documnet stored to simple store
    * @type {String}
    */
  this.fileStoreSimple = ''
    /**
    * person (ref -> cdn_person)
    * @type {Number}
    */
  this.person = 0
    /**
    * employee (ref -> cdn_employee)
    * @type {Number}
    */
  this.employee = 0
    /**
    *  (ref -> uba_user)
    * Row owner
    *
    * @type {Number}
    */
  this.mi_owner = 0
    /**
    *
    * Creation date
    *
    * @type {Date}
    */
  this.mi_createDate = new Date()
    /**
    *  (ref -> uba_user)
    * User who create row
    *
    * @type {Number}
    */
  this.mi_createUser = 0
    /**
    *
    * Modification date
    *
    * @type {Date}
    */
  this.mi_modifyDate = new Date()
    /**
    *  (ref -> uba_user)
    * User who modify row
    *
    * @type {Number}
    */
  this.mi_modifyUser = 0
}

/**
* DocusignEnvelopeTest
* @mixes EventEmitter
* @mixes RequiredModule
*/
var tst_docusign = {
  /**
   * Reference to entity metadata
   * @type {TubEntity}
   */
  entity: null
}

/**
* Attributes of "DocusignEnvelopeTest"
* @class
*/
function tst_docusign_object () {
    /**
    *
    *
    * @type {Number}
    */
  this.ID = 0
    /**
    * name
    * @type {String}
    */
  this.name = ''
    /**
    * Envelope (ref -> dses_envelope)
    * Envelope
    * @type {Number}
    */
  this.envelope = 0
    /**
    *  (ref -> uba_user)
    * Row owner
    *
    * @type {Number}
    */
  this.mi_owner = 0
    /**
    *
    * Creation date
    *
    * @type {Date}
    */
  this.mi_createDate = new Date()
    /**
    *  (ref -> uba_user)
    * User who create row
    *
    * @type {Number}
    */
  this.mi_createUser = 0
    /**
    *
    * Modification date
    *
    * @type {Date}
    */
  this.mi_modifyDate = new Date()
    /**
    *  (ref -> uba_user)
    * User who modify row
    *
    * @type {Number}
    */
  this.mi_modifyUser = 0
}

/**
* DocusignDocument
* @mixes EventEmitter
* @mixes RequiredModule
*/
var tst_docusign_doc = {
  /**
   * Reference to entity metadata
   * @type {TubEntity}
   */
  entity: null
}

/**
* Attributes of "DocusignDocument"
* @class
*/
function tst_docusign_doc_object () {
    /**
    *
    *
    * @type {Number}
    */
  this.ID = 0
    /**
    * Envelope (ref -> tst_docusign)
    * Envelope
    * @type {Number}
    */
  this.envelope = 0
    /**
    * Document (ref -> tst_document)
    * Document
    * @type {Number}
    */
  this.document = 0
    /**
    *  (ref -> uba_user)
    * Row owner
    *
    * @type {Number}
    */
  this.mi_owner = 0
    /**
    *
    * Creation date
    *
    * @type {Date}
    */
  this.mi_createDate = new Date()
    /**
    *  (ref -> uba_user)
    * User who create row
    *
    * @type {Number}
    */
  this.mi_createUser = 0
    /**
    *
    * Modification date
    *
    * @type {Date}
    */
  this.mi_modifyDate = new Date()
    /**
    *  (ref -> uba_user)
    * User who modify row
    *
    * @type {Number}
    */
  this.mi_modifyUser = 0
}

/**
* DocusignReceiver
* @mixes EventEmitter
* @mixes RequiredModule
*/
var tst_docusign_receiver = {
  /**
   * Reference to entity metadata
   * @type {TubEntity}
   */
  entity: null
}

/**
* Attributes of "DocusignReceiver"
* @class
*/
function tst_docusign_receiver_object () {
    /**
    *
    *
    * @type {Number}
    */
  this.ID = 0
    /**
    * Envelope (ref -> tst_docusign)
    * Envelope
    * @type {Number}
    */
  this.envelope = 0
    /**
    * Receiver (ref -> uba_user)
    * Receiver
    * @type {Number}
    */
  this.receiver = 0
    /**
    *  (ref -> uba_user)
    * Row owner
    *
    * @type {Number}
    */
  this.mi_owner = 0
    /**
    *
    * Creation date
    *
    * @type {Date}
    */
  this.mi_createDate = new Date()
    /**
    *  (ref -> uba_user)
    * User who create row
    *
    * @type {Number}
    */
  this.mi_createUser = 0
    /**
    *
    * Modification date
    *
    * @type {Date}
    */
  this.mi_modifyDate = new Date()
    /**
    *  (ref -> uba_user)
    * User who modify row
    *
    * @type {Number}
    */
  this.mi_modifyUser = 0
}

/**
* test fts data with scope&#x3D;Connection non multi lang
* @mixes EventEmitter
* @mixes RequiredModule
*/
var tst_ftsconnection = {
  /**
   * Reference to entity metadata
   * @type {TubEntity}
   */
  entity: null
}

/**
* Attributes of "test fts data with scope&#x3D;Connection non multi lang"
* @class
*/
function tst_ftsconnection_object () {
    /**
    *
    *
    * @type {Number}
    */
  this.ID = 0
    /**
    * Caption
    * @type {String}
    */
  this.caption = ''
    /**
    * Registration date
    * @type {Date}
    */
  this.regDate = new Date()
}

/**
* test fts data with scope&#x3D;Connection multi lang
* @mixes EventEmitter
* @mixes RequiredModule
*/
var tst_ftsconnection_ml = {
  /**
   * Reference to entity metadata
   * @type {TubEntity}
   */
  entity: null
}

/**
* Attributes of "test fts data with scope&#x3D;Connection multi lang"
* @class
*/
function tst_ftsconnection_ml_object () {
    /**
    *
    *
    * @type {Number}
    */
  this.ID = 0
    /**
    * Caption
    * @type {String}
    */
  this.caption = ''
    /**
    * Registration date
    * @type {Date}
    */
  this.regDate = new Date()
}

/**
* test fts data with scope&#x3D;Entity non multi lang
* @mixes EventEmitter
* @mixes RequiredModule
*/
var tst_ftsentity = {
  /**
   * Reference to entity metadata
   * @type {TubEntity}
   */
  entity: null
}

/**
* Attributes of "test fts data with scope&#x3D;Entity non multi lang"
* @class
*/
function tst_ftsentity_object () {
    /**
    *
    *
    * @type {Number}
    */
  this.ID = 0
    /**
    * Caption
    * @type {String}
    */
  this.caption = ''
    /**
    * Registration date
    * @type {Date}
    */
  this.regDate = new Date()
}

/**
* ID mapped
* @mixes EventEmitter
* @mixes RequiredModule
*/
var tst_IDMapping = {
  /**
   * Reference to entity metadata
   * @type {TubEntity}
   */
  entity: null
}

/**
* Attributes of "ID mapped"
* @class
*/
function tst_IDMapping_object () {
    /**
    * Ідентифікатор запису
    * Ідентифікатор запису
    * @type {Number}
    */
  this.ID = 0
    /**
    * Code
    * Internal code
    * @type {String}
    */
  this.code = ''
}

/**
* ub test main data
* @mixes EventEmitter
* @mixes RequiredModule
*/
var tst_maindata = {
  /**
   * Reference to entity metadata
   * @type {TubEntity}
   */
  entity: null
}

/**
* Attributes of "ub test main data"
* @class
*/
function tst_maindata_object () {
    /**
    *  (ref -> tst_mainunity)
    *
    * @type {Number}
    */
  this.ID = 0
    /**
    * Code
    * @type {String}
    */
  this.code = ''
    /**
    * Caption
    * @type {String}
    */
  this.caption = ''
    /**
    * complexCaption
    * @type {String}
    */
  this.complexCaption = ''
    /**
    * nonNullDict_ID (ref -> tst_dictionary)
    * @type {Number}
    */
  this.nonNullDict_ID = 0
    /**
    * nullDict_ID (ref -> tst_dictionary)
    * @type {Number}
    */
  this.nullDict_ID = 0
    /**
    * enumValue
    * @type {String}
    */
  this.enumValue = ''
    /**
    * dateTimeValue
    * @type {Date}
    */
  this.dateTimeValue = new Date()
    /**
    * booleanValue
    * @type {Boolean}
    */
  this.booleanValue = undefined
    /**
    * test many data (ref -> tst_dictionary)
    * @type {String}
    */
  this.manyValue = ''
    /**
    * test 2d many data (ref -> tst_dictionary)
    * @type {String}
    */
  this.manyValue2 = ''
    /**
    * BigInt
    * @type {Number}
    */
  this.bigintValue = 0
    /**
    *  (ref -> uba_user)
    * Row owner
    *
    * @type {Number}
    */
  this.mi_owner = 0
    /**
    *
    * Creation date
    *
    * @type {Date}
    */
  this.mi_createDate = new Date()
    /**
    *  (ref -> uba_user)
    * User who create row
    *
    * @type {Number}
    */
  this.mi_createUser = 0
    /**
    *
    * Modification date
    *
    * @type {Date}
    */
  this.mi_modifyDate = new Date()
    /**
    *  (ref -> uba_user)
    * User who modify row
    *
    * @type {Number}
    */
  this.mi_modifyUser = 0
    /**
    *
    * Deletion date
    *
    * @type {Date}
    */
  this.mi_deleteDate = new Date()
    /**
    *  (ref -> uba_user)
    * User who delete row
    *
    * @type {Number}
    */
  this.mi_deleteUser = 0
}

/**
* tst_mainunity
* @mixes EventEmitter
* @mixes RequiredModule
*/
var tst_mainunity = {
  /**
   * Reference to entity metadata
   * @type {TubEntity}
   */
  entity: null
}

/**
* Attributes of "tst_mainunity"
* @class
*/
function tst_mainunity_object () {
    /**
    *
    *
    * @type {Number}
    */
  this.ID = 0
    /**
    * Code
    * @type {String}
    */
  this.code = ''
    /**
    * Caption
    * @type {String}
    */
  this.caption = ''
    /**
    *  (ref -> uba_user)
    * Row owner
    *
    * @type {Number}
    */
  this.mi_owner = 0
    /**
    *
    * Creation date
    *
    * @type {Date}
    */
  this.mi_createDate = new Date()
    /**
    *  (ref -> uba_user)
    * User who create row
    *
    * @type {Number}
    */
  this.mi_createUser = 0
    /**
    *
    * Modification date
    *
    * @type {Date}
    */
  this.mi_modifyDate = new Date()
    /**
    *  (ref -> uba_user)
    * User who modify row
    *
    * @type {Number}
    */
  this.mi_modifyUser = 0
    /**
    *
    * Deletion date
    *
    * @type {Date}
    */
  this.mi_deleteDate = new Date()
    /**
    *  (ref -> uba_user)
    * User who delete row
    *
    * @type {Number}
    */
  this.mi_deleteUser = 0
    /**
    *
    *
    * @type {String}
    */
  this.mi_unityEntity = ''
}

/**
* tst_ODataRef
* @mixes EventEmitter
* @mixes RequiredModule
*/
var tst_ODataRef = {
  /**
   * Reference to entity metadata
   * @type {TubEntity}
   */
  entity: null
}

/**
* Attributes of "tst_ODataRef"
* @class
*/
function tst_ODataRef_object () {
    /**
    *
    *
    * @type {Number}
    */
  this.ID = 0
    /**
    * Code
    * Code
    * @type {String}
    */
  this.code = ''
    /**
    *  (ref -> tst_ODataSimple)
    * @type {Number}
    */
  this.refColumn = 0
    /**
    * Simple
    * Document stored to simple store
    * @type {String}
    */
  this.storeColumn = ''
}

/**
* tst_ODataSimple
* @mixes EventEmitter
* @mixes RequiredModule
*/
var tst_ODataSimple = {
  /**
   * Reference to entity metadata
   * @type {TubEntity}
   */
  entity: null
}

/**
* Attributes of "tst_ODataSimple"
* @class
*/
function tst_ODataSimple_object () {
    /**
    *
    *
    * @type {Number}
    */
  this.ID = 0
    /**
    * Code
    * Code
    * @type {String}
    */
  this.code = ''
    /**
    * Caption
    * Caption
    * @type {String}
    */
  this.caption = ''
    /**
    * filterValue
    * @type {Number}
    */
  this.filterValue = 0
    /**
    * Currency Data
    * @type {Number}
    */
  this.currencyValue = 0
    /**
    * Назва
    * @type {String}
    */
  this.calculated = ''
    /**
    * Test boolean column
    * @type {Boolean}
    */
  this.booleanColumn = undefined
    /**
    *
    * @type {String}
    */
  this.enumColumn = ''
    /**
    * Document date
    * @type {Date}
    */
  this.dateColumn = new Date()
}

/**
* Test PDF sign
* @mixes EventEmitter
* @mixes RequiredModule
*/
var tst_pdfSign = {
  /**
   * Reference to entity metadata
   * @type {TubEntity}
   */
  entity: null
}

/**
* Attributes of "Test PDF sign"
* @class
*/
function tst_pdfSign_object () {
}

/**
* Test servises
* @mixes EventEmitter
* @mixes RequiredModule
*/
var tst_service = {
  /**
   * Reference to entity metadata
   * @type {TubEntity}
   */
  entity: null
}

/**
* Attributes of "Test servises"
* @class
*/
function tst_service_object () {
}
